---
abstract: 'Module loader for one liner.'
author:
  - 'Masayuki Matsuki E<lt>y.songmu@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: L
no_index:
  directory:
    - inc
provides:
  L:
    file: lib/L.pm
    version: 0.01
requires:
  Module::Load: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
